

captcha:
  image-width: 240
  image-height: 80
  key-long: 4
  open-captcha: 0  # 0代表一直开启，大于0代表限制次数
  open-captcha-timeout: 3600  # open-captcha大于0时才生效

jwt:
  signing-key: unicrm
  expires-time: 7d
  buffer-time: 1d
  issuer: unicrm

logger:
  level: debug
  director: log
  format: console
  stacktrace-key: stacktrace
  prefix: "[unicrm]"
  log-in-console: true
  max-age: 28
  show-line: true

system:
  run-mode: debug
  addr: 8000
  use-redis: true
  router-prefix: "/api/v1"
  redis-name: default
  use-multipoint: false

general-db:
  db-type: mysql
  host: 106.12.59.2
  port: 5535
  user: unicrm
  password: 123456
  db-name: unicrm
  config: charset=utf8mb4&parseTime=True&loc=Local
  prefix: "unicrm_"
  singular: true
  max-idle-conns: 10
  max-open-conns: 100
  engine: InnoDB
  log-mode: warn  # silent（无日志），error（仅错误日志），warn（警告及以上），info（信息及以上）

redis-list:
  - name: default  # 数据库的名称,注意: name 需要在 redis-list 中唯一
    addr: 106.12.59.2:6379  # 单机模式
    password: "123456"
    db: 0
    useCluster: false  # 集群模式，使用集群模式时，单机模式配置无效
    clusterAddrs:
      - "106.12.59.2:6379"
      - "106.12.59.2:6379"
  - name: cache           
    addr: 106.12.59.2:6379  # 单机模式
    password: "123456"
    db: 0
    useCluster: false     # 集群模式，使用集群模式时，单机模式配置无效
    clusterAddrs:
      - "106.12.59.2:6379"
      - "106.12.59.2:6379"